#!/bin/bash
# theme.sh - Tema semantico de MEAL, construido sobre colors.sh
MEAL_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$MEAL_LIB_DIR/colors.sh"

MEAL_THEME_BORDER="$MEAL_COLOR_PRIMARY"
MEAL_THEME_TITLE="$MEAL_COLOR_PRIMARY"
MEAL_THEME_SUCCESS="$MEAL_COLOR_SUCCESS"
MEAL_THEME_ERROR="$MEAL_COLOR_ERROR"
MEAL_THEME_WARNING="$MEAL_COLOR_WARNING"
MEAL_THEME_MUTED="$MEAL_COLOR_MUTED"
